{{- if .Values.rollout.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: auth-service-preview
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: auth-service
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
{{- end }}
