apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-service
  labels:
    {{- include "session-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: session-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: session-service
    spec:
      containers:
        - name: session-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          {{- if .Values.externalSecret.enabled }}
          envFrom:
            - secretRef:
                name: session-service-env
          {{- end }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
