apiVersion: apps/v1
kind: Deployment
metadata:
  name: shooter
  labels:
    {{- include "shooter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: shooter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: shooter
    spec:
      containers:
        - name: shooter
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.targetPort }}
